---
## checkversions.yml
## version 0.4
## Tested on Ubuntu Server 16.04.03. Tested on Centos 7.3.1611
## Doesn not work on FreeNAS 9.10 probably because of different Python path
## The goal is to check all computers for a certain version of specific software.
## Usually because it's vulnerable to attack.

- name: Check if software is installed. "changed" means yes. "failed" means no.
  shell: which {{sware}}
  ignore_errors: no
  register: softwarecheck
  changed_when: 
    - softwarecheck.stdout != ""
    - softwarecheck.stdout != "\r\n"
#  when: "'Ubuntu' in ansible_distribution"

- debug: msg="{{sware}} is installed at {{softwarecheck.stdout}}"
  when: "'/' in softwarecheck.stdout"

  

- name: Check version number. "ok" means yes. "failed" means no.
  shell: exim4 --version | grep "{{svers}}"
  register: softwareversion
  when: "'/' in softwarecheck.stdout"

- debug: msg="{{softwareversion.stdout}}"
  when: "'/' in softwarecheck.stdout"





...
