---
# file: provisionproxmox.yml

- hosts: me

  pre_tasks:
    - name: Alert banner
      debug:
        msg:
          - " #     #                     #                                    ### "
          - " #     # ###### #   #        #       #  ####  ##### ###### #    # ### "
          - " #     # #       # #         #       # #        #   #      ##   # ### "
          - " ####### #####    #          #       #  ####    #   #####  # #  #  #  "
          - " #     # #        #   ###    #       #      #   #   #      #  # #     "
          - " #     # #        #   ###    #       # #    #   #   #      #   ## ### "
          - " #     # ######   #    #     ####### #  ####    #   ###### #    # ### "
          - "                      #                                               "
          - "       I   h a v e   s o m e   q u e s t i o n s   f o r   y o u      "

    # - pause:
    #     seconds: 5

    - name: Which OS do you want to provision? Here's your vinilla options.
      debug:
        msg:
          - "press 01 for Ubuntu 18.04 - Bionic"
          - "press 02 for Ubuntu 16.04 - Xenial"
          - ""
          - "press 10 for Debian 9 - Stretch"
          - ""
          - "press 20 for CentOS 7 - Maipo"
          - ""
          - "press 30 for OpenSUSE 15 - Leap"
          - "press 31 for OpenSUSE 15 - Tumbleweed"
          - ""
          - "press 40 for Mint 19 - Tara"
          - ""
          - "press 80 for Windows 2016 - 1809"
          - ""
          - "press 90 for Windows 10 - 1809"

     - pause:
         seconds: 10

    - name: Which OS do you want to provision? Here's your options of OSs pre-configured to run certain services
      debug:
        msg:
          - "press 101 for Ansible"
          - "press 102 for Domain Controller"
          - "press 103 for Samba"
          - "press 104 for Jenkins"
          - "press 105 for LAMP"
          - "press 106 for Mattermost"
          - "press 107 for MediaWiki"
          - "press 108 for NextCloud"
          - "press 109 for OpenLDAP"
          - "press 110 for PostgreSQL"
          - "press 111 for SuiteCRM"
          - "press 112 for Syncthing"
          - "press 113 for Torrent"
          - "press 114 for WordPress"
          - "press 115 for Zoneminder"
          - "press 116 for iceScrum"
          - ""
          - "   A n s w e r   n o w :   "

     - pause:
         seconds: 1


- import_playbook: provisionproxmox-human_questions.yml
...
